### ISSUE TITLE
Is the database delayed?

### ISSUE THREAD

**Issue by nasht00** [jlvcm/stremio-yts#3]
On Stremio when I look at "Terminator: Dark Fate", it says "no streams were found".

I thought YTS probably hasn't uploaded it yet. So out of curiosity I went to the YTS website and... it's there already!

Same thing for "Honey Boy" which is also a new release.

Older releases however seem to work fine.

Anyone has any insight on that?

**Comment by jlvcm** [comment]
changed the servers ,and caching

there could be a delay between 12h to 24h, depending on the last time you open that movie on stremio or the last person access that movie

let me know if this issue is still happening and i'll open this ticket again,
thanks
